.github/PULL_REQUEST_TEMPLATE.md

[As a Developer, I want a Pull Request template with the definition of done in it](https://trello.com/c/pULBvXSF/31-as-a-developer-i-want-a-pull-request-template-with-the-definition-of-done-in-it)
This story adds the merge request template to the .github folder

Add merge request template

---

app/views/application/_navigation.html.slim

invalid text instad of alt html attribute fixed

---

app/assets/stylesheets/_main.scss
app/controllers/clients_controller.rb
app/models/client.rb
app/models/schedule.rb
app/views/application/_navigation.html.slim
app/views/clients/_availability_fields.html.slim
app/views/clients/_client.html.slim
app/views/clients/_form.html.slim
app/views/clients/_language_skill_fields.html.slim
app/views/clients/_relative_fields.html.slim
app/views/clients/index.html.slim
app/views/clients/new.html.slim
app/views/clients/show.html.slim
db/migrate/20170421070309_create_schedules.rb
db/migrate/20170421104115_remove_availability_from_clients.rb
db/schema.rb
test/factories/availabilities.rb
test/models/availability_test.rb

WIP: Features/create client rebase now

---

app/views/users/_form.html.slim
test/system/users_test.rb

As a User, I want to confirm an Invitation to another User

---

app/views/profiles/_form.html.slim

fix the language not translated in profiles form

---

app/controllers/application_controller.rb
app/policies/user_policy.rb
app/views/application/_navigation.html.slim
config/routes.rb

fix social_worker cannot see other users

---

app/views/clients/_form.html.slim

fix client state view

---

app/controllers/clients_controller.rb
app/helpers/application_helper.rb
app/models/language_skill.rb
app/views/application/_navigation.html.slim
app/views/clients/_availability_fields.html.slim
app/views/clients/_client.html.slim
app/views/clients/_form.html.slim
app/views/clients/_language_skill_fields.html.slim
app/views/clients/_language_skill_show.html.slim
app/views/clients/_relative_fields.html.slim
app/views/clients/_relatives_show.html.slim
app/views/clients/edit.html.slim
app/views/clients/index.html.slim
app/views/clients/new.html.slim
app/views/clients/show.html.slim
app/views/profiles/_form.html.slim
app/views/profiles/show.html.slim
app/views/users/_form.html.slim
app/views/users/_user.html.slim
app/views/users/index.html.slim
app/views/users/show.html.slim
config/initializers/countries.rb
config/initializers/locale.rb
config/locales/de.yml
config/locales/en.yml

https://trello.com/c/S2hGGyeM/16-as-a-developer-i-want-to-add-missing-translations

Add translations

---

README.md
app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/models/user.rb
app/views/application/_navigation.html.slim
app/views/clients/_form.html.slim
app/views/clients/_language_skill_fields.html.slim
app/views/clients/_language_skill_show.html.slim
app/views/clients/_relative_fields.html.slim
app/views/clients/_relatives_show.html.slim
app/views/clients/edit.html.slim
app/views/clients/show.html.slim
app/views/profiles/show.html.slim
app/views/users/_form.html.slim
config/locales/de.yml
config/locales/en.yml
config/routes.rb
db/seeds.rb
test/models/user_test.rb
test/policies/client_policy_test.rb
test/policies/profile_policy_test.rb
test/policies/user_policy_test.rb
test/system/department_manager_test.rb
test/system/users_test.rb

@chrysalag @kitsane @nuritnt:
I've picked all commits to #40 , because otherwise it's translation regrouping will be nifty to get merged. So #40 containes all features and tests from #39 with additional translation fixes on top...
https://trello.com/c/aFpeDRzf/24-as-an-superadmin-i-want-to-create-users-responsible-for-a-department

WIP: Features/department manager

---

app/models/application_record.rb
app/models/user.rb
db/migrate/20170511135554_add_deleted_at_to_all_models.rb
db/schema.rb
test/system/clients_test.rb

WIP: Features/deactivate entries

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/departments_controller.rb
app/models/user.rb
app/policies/department_policy.rb
app/views/application/_navigation.html.slim
app/views/departments/_form.html.slim
config/locales/en.yml
test/controllers/departments_controller_test.rb
test/models/department_test.rb
test/policies/client_policy_test.rb
test/policies/department_policy_test.rb
test/policies/profile_policy_test.rb
test/policies/user_policy_test.rb
test/system/departments_test.rb
test/test_helper.rb

As a Department Manager and Superadmin, I want to manage Departments
- Department Managers can't change the assigned Department Manager
- As Department Manager there is a link in the Navbar to his department
- Department Managers can update the department's fields
[Link to story in trello](https://trello.com/c/dtIXQFBa/13-as-a-department-manager-and-superadmin-i-want-to-manage-departments-sp-5)
-  ~~Seeds created~~
-  ~~Translated~~
Review by Team

As a Department Manager and Superadmin, I want to manage Departments

---

config/locales/de.yml
config/locales/en.yml

- document separator
- emoji unicode escaped
Review by Team

fixed validity

---

.rubocop.yml
Gemfile
Gemfile.lock
app/models/client.rb
app/models/concerns/state_collection.rb
app/models/contact_email.rb
app/models/language_skill.rb
app/models/volunteer.rb
db/seeds.rb

[Link to story in trello](https://trello.com/c/uUYKStYl/21-as-a-developer-i-want-to-have-extended-seeds-so-that-i-can-see-problems-with-the-content-better)
Review by Team

As a developer, I want to have extended seeds, so that I can see problems with the content better.

---

app/views/language_skills/_show.html.slim
app/views/relatives/_show.html.slim

[Link to story in trello](https://trello.com/c/YW6DFbLP/6-as-a-developer-i-want-to-process-through-the-whole-application-and-provide-feedback-1h)
Review by Team

fix lang and relative show view

---

app/views/language_skills/_show.html.slim
app/views/relatives/_show.html.slim

Revert "fix lang and relative show view"

---

app/assets/javascripts/rejection.js
app/controllers/concerns/nested_attributes.rb
app/controllers/volunteer_applications_controller.rb
app/controllers/volunteers_controller.rb
app/models/user.rb
app/models/volunteer.rb
app/policies/volunteer_policy.rb
app/views/application/_navigation.html.slim
app/views/language_skills/_form.html.slim
app/views/relatives/_form.html.slim
app/views/schedules/_form.html.slim
app/views/volunteer_applications/new.html.slim
app/views/volunteers/_form.html.slim
app/views/volunteers/edit.html.slim
app/views/volunteers/new.html.slim
app/views/volunteers/show.html.slim
config/locales/de.yml
config/locales/en.yml
db/migrate/20170526130435_add_user_to_volunteers.rb
db/migrate/20170526132032_change_column_default_volunteers_state.rb
db/migrate/20170526205852_add_rejection_type_to_volunteers.rb
db/migrate/20170526205943_add_rejection_text_to_volunteers.rb
db/schema.rb
test/application_system_test_case.rb
test/policies/volunteer_policy_test.rb
test/system/department_manager_test.rb
test/system/socialworker_test.rb
test/system/users_test.rb
test/system/volunteer_applications_test.rb
test/system/volunteers_test.rb

[Link to story in trello](https://trello.com/c/A91i0pkG/15-as-a-superadmin-i-want-to-process-volunteers-sp-3)
Review by Team

Process volunteers

---

app/views/language_skills/_show.html.slim
app/views/relatives/_show.html.slim

[Link to story in trello](https://trello.com/c/YW6DFbLP/6-as-a-developer-i-want-to-process-through-the-whole-application-and-provide-feedback-1h)
Review by Team

show rel and lang view fixed

---

app/controllers/clients_controller.rb
app/controllers/profiles_controller.rb
app/controllers/users_controller.rb

Simplifing authorization

---

app/models/volunteer.rb
app/views/volunteers/_form.html.slim
db/seeds.rb

make state collection independet from volunteer

---

app/controllers/application_controller.rb
app/controllers/volunteers_controller.rb
app/models/user.rb
app/policies/volunteer_policy.rb
app/views/application/_navigation.html.slim

Volunteer gets directly to volunteers_controller#show after login

---

db/migrate/20170608102534_create_partial_unique_index_for_user_table.rb
db/schema.rb

partial index for users email

---

Gemfile
Gemfile.lock

all tests seem to run green with this
Review by Team

removed sass-rails to be pulled from github and ran bundle update

---

app/helpers/application_helper.rb
app/views/clients/_form.html.slim
app/views/departments/_form.html.slim
app/views/devise/invitations/edit.html.slim
app/views/devise/invitations/new.html.slim
app/views/devise/passwords/edit.html.slim
app/views/devise/passwords/new.html.slim
app/views/profiles/_form.html.slim
app/views/users/_form.html.slim
app/views/volunteers/_form.html.slim
lib/templates/slim/scaffold/_form.html.slim

simple form error notification helper

---

app/helpers/application_helper.rb
app/views/clients/edit.html.slim
app/views/clients/index.html.slim
app/views/clients/new.html.slim
app/views/clients/show.html.slim
app/views/departments/edit.html.slim
app/views/departments/index.html.slim
app/views/departments/new.html.slim
app/views/departments/show.html.slim
app/views/profiles/edit.html.slim
app/views/profiles/show.html.slim
app/views/users/index.html.slim
app/views/users/show.html.slim
app/views/volunteers/edit.html.slim
app/views/volunteers/index.html.slim
app/views/volunteers/new.html.slim
app/views/volunteers/show.html.slim

Generic form navigation links (as buttons) helper

---

app/models/user.rb
app/views/departments/_form.html.slim
app/views/departments/show.html.slim
app/views/profiles/edit.html.slim
config/locales/en.yml
test/factories/clients.rb
test/factories/departments.rb
test/factories/profiles.rb
test/factories/users.rb
test/factories/volunteers.rb
test/system/departments_test.rb
test/test_helper.rb

[Link to story in trello](https://trello.com/c/O3MG8ERt/11-as-a-user-i-want-to-see-improvements-on-departments-2)
Review by Team

As a User, I want to see improvements on departments [2]

---

app/helpers/application_helper.rb

remove duplicate method single_col_xs

---

app/models/contact.rb
app/views/clients/_client.html.slim
app/views/clients/index.html.slim
config/locales/de.yml
config/locales/en.yml
db/seeds.rb

update relation seeds, fix typo and add missing translation

---

app/models/language_skill.rb
app/models/relative.rb

not sure if it really works. Maybe our tests will show...
Review by Team

try fixing empty value passed to I18n.t with conditional

---

.github/PULL_REQUEST_TEMPLATE.md

new pull request template

---

config/locales/de.yml

[Link to story in trello](https://trello.com/c/ZWgabLiy/13-as-a-user-i-want-consistent-naming-of-volunteers-1)
Review by Team

As a User, I want consistent naming of Volunteers [1]

---

app/views/volunteers/index.html.slim

Volunteer name and city sorting fixed

---

app/assets/stylesheets/layout/_content.scss
app/models/volunteer.rb
app/views/assignments/_duration_select.html.slim
app/views/assignments/_gender_select.html.slim
app/views/assignments/find_volunteer.html.slim

Fix no route & fix buggy filtering

---

app/views/clients/show.html.slim
config/locales/de.yml

add missing fields & translations

---

app/controllers/assignments_controller.rb
app/models/assignment.rb
app/models/user.rb
app/views/assignments/_assignment.html.slim
app/views/assignments/_form.html.slim
app/views/assignments/index.html.slim
config/locales/de.yml
config/locales/en.yml
db/migrate/20170712141707_add_state_to_assignments.rb
db/migrate/20170712144909_add_user_to_assignments.rb
db/migrate/20170713134956_rename_user_id_to_creator_id_on_assignments.rb
db/schema.rb
test/factories/assignments.rb
test/factories/creator.rb
test/models/client_test.rb
test/system/assignments_test.rb

- ~[ ] Readme updated if needed~
- ~[ ] Seeds created~

add attributes to assignments

---

app/views/assignments/show.html.slim
config/locales/de.yml
config/locales/en.yml
db/schema.rb

- ~[ ] Radme updated if needed~
- ~[ ] Story under test~
- ~[ ] Seeds created~

replace pdf

---

app/controllers/clients_controller.rb
app/controllers/departments_controller.rb
app/controllers/profiles_controller.rb
app/controllers/volunteer_applications_controller.rb
app/controllers/volunteers_controller.rb
app/models/client.rb
app/models/concerns/build_contact_relation.rb
app/models/concerns/build_schedules_relation.rb
app/models/department.rb
app/models/profile.rb
app/models/volunteer.rb
test/models/client_test.rb
test/models/department_test.rb
test/models/volunteer_test.rb

Just soing something that has always hurt me, when I looked at the thing. SCNR.

Models that require Contact or Schedule to be built on them, take care of this themselves

---

app/helpers/application_helper.rb
app/mailers/volunteer_mailer.rb
app/models/volunteer.rb
app/views/assignments/_gender_select.html.slim
app/views/assignments/_without_client.html.slim
app/views/assignments/find_volunteer.html.slim
app/views/clients/_client.html.slim
app/views/clients/show.html.slim
app/views/volunteer_mailer/welcome_email.html.slim
app/views/volunteer_mailer/welcome_email.text.slim
app/views/volunteers/show.html.slim
config/initializers/countries.rb
test/system/volunteers_test.rb

- ~[ ] Readme updated if needed~
- ~[ ] Story under test~
- ~[ ] Seeds created~
- ~[ ] Translated~

fix filtering and sorting in find volunteer

---

.github/PULL_REQUEST_TEMPLATE.md

just minor changes to the PR template - see the example right here

---

app/controllers/assignments_controller.rb
app/controllers/volunteers_controller.rb
app/helpers/application_helper.rb
app/models/client.rb
app/policies/assignment_policy.rb
app/policies/volunteer_policy.rb
app/views/assignments/_age_request_select.html.slim
app/views/assignments/_gender_request_select.html.slim
app/views/assignments/_language_skills_language_select.html.slim
app/views/assignments/find_client.html.slim
app/views/clients/_client.html.slim
app/views/clients/_columns.html.slim
app/views/clients/_form.html.slim
app/views/clients/_request.html.slim
app/views/volunteers/_columns.html.slim
app/views/volunteers/_volunteer.html.slim
app/views/volunteers/_without_client.html.slim
app/views/volunteers/index.html.slim
app/views/volunteers/without_clients.html.slim
config/locales/de.yml
config/locales/en.yml
config/routes.rb
db/seeds.rb
test/models/volunteer_test.rb
test/policies/assignment_policy_test.rb
test/policies/volunteer_policy_test.rb
test/system/assignments_test.rb
test/system/clients_test.rb

matching volunteer side

---

app/helpers/application_helper.rb
app/views/application/_index_actions.html.slim
app/views/assignments/_assignment.html.slim
app/views/assignments/index.html.slim
app/views/clients/_client.html.slim
app/views/clients/_columns.html.slim
app/views/clients/index.html.slim
app/views/departments/index.html.slim
app/views/layouts/application.html.slim
app/views/volunteer_emails/index.html.slim
app/views/volunteers/_columns.html.slim
app/views/volunteers/_volunteer.html.slim
app/views/volunteers/index.html.slim
config/locales/de.yml
config/locales/en.yml
test/system/index_action_partials_test.rb

- generic partial that ads columns for action links within index listingsa
- print link, that opens new window/tab that executs browsers print function

generic resource index list actions partial

---

app/views/assignments/find_client.html.slim
app/views/volunteers/_columns.html.slim
app/views/volunteers/_volunteer.html.slim

Use of volunteer index partial for show volunteer at find client

---

app/views/assignments/show.html.slim
test/system/assignments_test.rb

Fix PDF generation with superadmin that has no profile

---

app/models/user.rb
app/models/volunteer.rb
app/models/volunteer_email.rb

reorder stuff in models - for better overview / readability

---

.rubocop.yml
app/models/client.rb
app/models/language_skill.rb
app/models/volunteer.rb
app/views/assignments/_language_skills_language_select.html.slim
app/views/language_skills/_fields.html.slim
test/system/clients_test.rb

language preselection

---

config/deploy/production.rb
config/deploy/staging.rb

change servers addresses

---

Gemfile
Gemfile.lock
app/assets/stylesheets/layout/_pdf.scss
app/views/assignments/show.html.slim

Make assignment pdf single page

---

app/controllers/application_controller.rb
app/controllers/assignments_controller.rb
app/controllers/clients_controller.rb
app/controllers/departments_controller.rb
app/controllers/journals_controller.rb
app/controllers/profiles_controller.rb
app/controllers/users_controller.rb
app/controllers/volunteer_applications_controller.rb
app/controllers/volunteer_emails_controller.rb
app/controllers/volunteers_controller.rb
app/models/assignment.rb
app/models/user.rb
app/policies/application_policy.rb
app/policies/application_scope.rb
app/policies/assignment_policy.rb
app/policies/client_policy.rb
app/policies/department_policy.rb
app/policies/journal_policy.rb
app/policies/profile_policy.rb
app/policies/user_policy.rb
app/policies/volunteer_application_policy.rb
app/policies/volunteer_email_policy.rb
app/policies/volunteer_policy.rb
test/policies/journal_policy_test.rb
test/policies/volunteer_application_policy_test.rb
test/policies/volunteer_email_policy_test.rb
test/test_helper.rb

Issue #132: Fix/policy completation and debugging trying to deal with 

---

.travis.yml

trying to get travis to cache phantomjs

---

app/views/assignments/show.html.slim
config/locales/de.yml
config/locales/en.yml

remove volunteer mobile on pdf

---

app/views/volunteers/_columns.html.slim
app/views/volunteers/_volunteer.html.slim
test/application_system_test_case.rb

add missing name on seeking client index and fix test

---

app/views/contacts/_show.html.slim
test/system/departments_test.rb
test/system/profiles_test.rb
test/system/volunteer_applications_test.rb
test/system/volunteers_test.rb

secondary phone only on clients show

---

app/views/clients/_client.html.slim
app/views/clients/index.html.slim
app/views/volunteers/_volunteer.html.slim
app/views/volunteers/index.html.slim
app/views/volunteers/show.html.slim
config/locales/de.yml
config/locales/en.yml
test/system/assignments_test.rb

make matching process consistent

---

Gemfile
Gemfile.lock
app/controllers/volunteers_controller.rb
app/views/clients/_columns.html.slim
app/views/clients/index.html.slim
app/views/clients/need_accompanying.html.slim
app/views/volunteers/_columns.html.slim
app/views/volunteers/index.html.slim
app/views/volunteers/seeking_clients.html.slim
config/application.rb
test/system/assignments_test.rb
test/system/clients_test.rb
test/system/volunteers_test.rb

Error with missing translation was:
```
I18n::MissingTranslationData at /clients
translation missing: de.will_paginate.page_gap
```
- both from gems
- volunteers also have pagination now

get pagination translated and with bootstrap elements in view

---

app/policies/volunteer_email_policy.rb

BugFix: add missing policy for volunteer new?

---

test/factories/contact_emails.rb
test/factories/contact_phones.rb

* ~[ ] Code quality checks are green~

remove unused factories

---

app/controllers/journals_controller.rb
app/models/journal.rb
app/views/journals/_form.html.slim
app/views/journals/_journal_block.html.slim
app/views/journals/index.html.slim
app/views/journals/show.html.slim
config/locales/de.yml
config/locales/en.yml
db/migrate/20170809112804_add_category_to_journals.rb
db/schema.rb
db/seeds.rb
test/factories/journals.rb
test/system/journals_test.rb

add categories to journals

---

app/views/journals/_journal_block.html.slim
app/views/journals/index.html.slim
app/views/journals/show.html.slim
config/locales/de.yml

use translation for journals

---

app/controllers/volunteer_emails_controller.rb
app/models/client.rb
app/models/journal.rb
app/models/volunteer.rb
app/models/volunteer_email.rb
app/views/assignments/_volunteer_index.html.slim
app/views/assignments/find_client.html.slim
app/views/volunteers/_show_excerpt.html.slim
app/views/volunteers/show.html.slim
config/locales/de.yml
config/locales/en.yml
test/system/assignments_test.rb

BugFix: single exerpt volunteer view

---

app/helpers/application_helper.rb

* ~[ ] Code quality checks are green~

remove unused permit collection

---

app/views/application/_navigation.html.slim
app/views/volunteers/edit.html.slim
app/views/volunteers/show.html.slim
config/locales/de.yml
config/locales/en.yml

Fixes volunteer homepage

---

app/views/volunteers/_volunteer.html.slim

show percent only if value is present

---

app/views/assignments/show.html.slim

fix nationality and status in tandem pdf

---

app/policies/application_policy.rb
app/policies/assignment_policy.rb
app/views/application/_index_actions.html.slim
app/views/assignments/_assignment.html.slim

volunteer can show their assignments

---

app/controllers/clients_controller.rb
app/views/clients/_columns.html.slim
app/views/clients/index.html.slim
app/views/clients/index.xlsx.axlsx
app/views/volunteers/_columns.html.slim
app/views/volunteers/index.html.slim
app/views/volunteers/index.xlsx.axlsx
config/locales/de.yml
config/locales/en.yml
test/integration/clients_xlsx_export_test.rb
test/system/assignments_test.rb
test/system/clients_filter_dropdowns_test.rb

Features/xls export/client

---

Gemfile.lock

bundle update and all tests seem to run smooth

---

app/controllers/volunteers_controller.rb
app/views/volunteers/_form.html.slim
app/views/volunteers/show.html.slim
config/locales/de.yml
config/locales/en.yml
db/migrate/20170824123715_add_bank_account_to_volunteer.rb
db/schema.rb
test/system/volunteers_test.rb

Volunteer can add bank account

---

app/controllers/assignments_controller.rb
app/models/assignment.rb
app/models/concerns/language_and_schedule_references.rb
app/models/import.rb
app/models/language_skill.rb
app/models/user.rb
config/initializers/paper_trail.rb
config/locales/de.yml
db/migrate/20170825144136_add_missing_fields_for_assignments.rb
db/schema.rb
lib/access_import/acc_utils.rb
lib/access_import/access_import.rb
lib/access_import/accessors/accessor.rb
lib/access_import/accessors/begleitete.rb
lib/access_import/accessors/fallstelle_teilnehmer.rb
lib/access_import/accessors/freiwilligen_einsaetze.rb
lib/access_import/accessors/personen_rolle.rb
lib/access_import/assignment_transform.rb
lib/access_import/client_transform.rb
lib/tasks/access.rake
test/factories/assignments.rb
test/models/client_test.rb

Begleitungen import

---

app/views/assignments/edit.html.slim
app/views/assignments/new.html.slim
app/views/departments/edit.html.slim
app/views/departments/new.html.slim
app/views/hours/edit.html.slim
app/views/hours/new.html.slim
app/views/profiles/edit.html.slim
app/views/volunteer_emails/edit.html.slim
app/views/volunteer_emails/new.html.slim

* ~[ ] Acceptance criteria are met~

remove double eq on render form

---

db/migrate/20170825144136_add_missing_fields_for_assignments.rb
db/migrate/20170831162818_get_over_with_assignment_migration_trouble.rb
db/schema.rb

Fix: try to get rid off assignment migration trouble, number 999

---

app/mailers/application_mailer.rb
config/initializers/devise.rb
test/mailers/volunteer_mailer_test.rb

Fix: Failing Mail Servers

---

config/locales/de.yml
config/locales/en.yml

add assignment states translations

---

app/views/assignment_journals/index.html.slim
app/views/hours/index.html.slim

add links to profiles

---

app/views/volunteers/show.html.slim
test/system/assignments_test.rb

BUGFIX: new assignment button not visible by volunteer

---

app/models/hour.rb
test/system/assignments_test.rb

minutes-dropdown-quarters

---

app/controllers/billing_expenses_controller.rb
app/models/billing_expense.rb
app/views/billing_expenses/_form.html.slim
app/views/billing_expenses/edit.html.slim
app/views/billing_expenses/index.html.slim
app/views/billing_expenses/show.html.slim
config/locales/de.yml
config/locales/en.yml
config/routes.rb
test/system/billing_expenses_test.rb

Features/Automatic Billing

---

app/models/billing_expense.rb

BUGFIX: billing hours computation

---

app/controllers/assignments_controller.rb
app/policies/assignment_policy.rb
app/views/assignments/_assignment.html.slim
app/views/assignments/_form.html.slim
config/locales/de.yml
config/locales/en.yml
db/migrate/20170907090939_add_confirmation_to_assignments.rb
db/schema.rb

Volunteer confirms hours and feedback submitted

---

test/factories/profiles.rb
test/models/factory_test.rb

Follow-up from https://github.com/panter/aoz-003/pull/196#discussion_r138134491

Add test for factories

---

config/locales/de.yml
config/locales/en.yml
test/system/certificates_test.rb
test/system/hours_test.rb

translation missing fixes

---

app/views/application/_index_actions.html.slim
app/views/assignments/_assignment.html.slim
test/system/volunteers_test.rb

BugFix: volunteer index partial has journal link

---

app/views/group_offers/_form.html.slim
config/locales/de.yml

BugFix(es) in group offers

---

app/models/contact.rb
test/models/user_test.rb
test/system/assignments_test.rb
test/system/index_action_partials_test.rb

ensuring updating email via the contact is also updated on user emails

user email update

---

app/controllers/group_offers_controller.rb
app/models/group_offer.rb
app/models/volunteer.rb
app/views/group_offers/_form.html.slim
app/views/group_offers/index.html.slim
app/views/group_offers/show.html.slim
config/locales/de.yml
db/migrate/20170922082857_create_group_offers_volunteers_join_table.rb
db/migrate/20170922120423_add_responsible_to_group_offer.rb
db/schema.rb
test/factories/group_offers.rb
test/models/volunteer_scopes_test.rb

Group Offers and Volunteers

---

app/controllers/assignments_controller.rb

Chores: dry assignment show action

---

app/models/volunteer.rb
app/views/group_offers/_form.html.slim

BugFix: Department manager sees no volunteers on group offer creation

---

app/controllers/billing_expenses_controller.rb
app/views/billing_expenses/show.pdf.slim

BugFix: billing expenses show pdf

---

app/controllers/group_offers_controller.rb
app/views/group_offers/index.html.slim
app/views/group_offers/show.html.slim

Feature: group offer as pdf

---

Capfile
app/models/reminder.rb

Fix: Reminders Cron & minor fixes

---

.rubocop.yml
app/models/assignment.rb
app/models/client.rb
app/models/performance_report.rb
app/models/volunteer.rb
test/factories/assignments.rb
test/factories/clients.rb
test/factories/volunteers.rb
test/models/group_offer_category_test.rb
test/models/performance_report_test.rb

Kennzahlen Report auf interne/externe Freiwillige anpassen

---

lib/access_import/access_import.rb
lib/tasks/access.rake

fix problem with access import user creation

---

app/controllers/group_offers_controller.rb
app/models/group_offer.rb
app/policies/group_offer_policy.rb
app/views/group_offers/_group_offers_block.html.slim
app/views/group_offers/archived.html.slim
app/views/group_offers/index.html.slim
app/views/group_offers/show.html.slim
config/locales/de.yml
config/locales/en.yml
config/routes.rb
db/migrate/20170928093844_add_active_to_group_offer.rb
db/schema.rb
test/system/group_offers_test.rb

Feature: activate-deactivate-GA

---

app/controllers/group_offer_categories_controller.rb
app/policies/group_offer_category_policy.rb
app/views/group_offers/_group_offers_block.html.slim
test/policies/group_offer_categories_policy_test.rb
test/system/group_offer_categories_test.rb

Upon request department managers were also added to create a group offer category

add department manager to categories scope and add tests

---

app/controllers/volunteers_controller.rb
app/models/reminder.rb
app/models/volunteer.rb
test/models/reminder_test.rb
test/models/volunteer_test.rb

Implement restrictions for external volunteers

---

app/views/group_offer_categories/index.html.slim

forgotten translation change

---

app/controllers/departments_controller.rb
app/models/group_offer.rb
app/policies/volunteer_policy.rb
app/views/departments/show.html.slim
config/locales/de.yml
config/locales/en.yml
db/seeds.rb

volunteer active on department listing

---

app/controllers/departments_controller.rb
app/models/group_offer.rb
app/policies/volunteer_policy.rb
app/views/departments/show.html.slim
config/locales/de.yml
config/locales/en.yml
db/seeds.rb

Revert "volunteer active on department listing"

---

app/controllers/concerns/group_assignments_attributes.rb
app/controllers/group_offers_controller.rb
app/models/assignment.rb
app/models/group_assignment.rb
app/models/group_assignment_log.rb
app/models/group_offer.rb
app/models/volunteer.rb
app/policies/application_policy.rb
app/policies/group_offer_policy.rb
app/views/assignments/_volunteer_index.html.slim
app/views/group_offers/_form.html.slim
app/views/group_offers/_group_assignment_fields.html.slim
app/views/group_offers/_group_offers_block.html.slim
app/views/group_offers/show.html.slim
app/views/volunteers/_group_assignments.html.slim
app/views/volunteers/_volunteer.html.slim
app/views/volunteers/show.html.slim
config/locales/de.yml
config/locales/en.yml
db/migrate/20171004144107_remove_responsible_from_group_offer.rb
db/migrate/20171004145120_create_group_assignments.rb
db/migrate/20171011151358_create_group_assignment_logs.rb
db/schema.rb
test/factories/group_offers.rb
test/models/volunteer_scopes_test.rb
test/policies/group_offers_policy_test.rb
test/system/group_offers_test.rb

Feature volunteer show has group offers

---

app/models/group_assignment.rb

fix group assignment callback

---

app/models/group_assignment.rb
app/models/volunteer.rb
app/views/volunteers/show.html.slim

hours were only available to work if there was an assignment, but not working only if group offer is existing. 
now it is also checking for entering the hours, if the assignments even started.

fix: assignment_hours

---

app/views/clients/index.xlsx.axlsx

fix client salutation xlsx

---

lib/access_import/access_import.rb

BugFix: change wrong acceptance value returned from handle_vol_state

---

config/deploy/production.rb
lib/access_import/access_import.rb

Merge develop master again

---

app/views/clients/index.xlsx.axlsx
config/locales/de.yml
config/locales/en.yml

fix client xlsx name

---

app/controllers/group_offers_controller.rb
app/views/group_offers/index.xlsx.axlsx
test/integration/archived_group_offers_export_test.rb
test/integration/group_offers_xlsx_export_test.rb

Fix: Archived group offers get also printed

---

config/initializers/email.rb

The url used in Password change email etc. is set from .env variable

---

app/controllers/group_offers_controller.rb
app/views/clients/index.xlsx.axlsx
app/views/group_offers/index.xlsx.axlsx
config/deploy/production.rb
config/initializers/email.rb
config/locales/de.yml
config/locales/en.yml
lib/access_import/access_import.rb
test/integration/archived_group_offers_export_test.rb
test/integration/group_offers_xlsx_export_test.rb

default_email_url from .env variable

---

app/models/group_offer.rb
app/views/volunteers/_group_assignments.html.slim
config/locales/de.yml
config/locales/en.yml
test/system/group_offers_test.rb

BugFix: volunteer show if group offer gets deleted

---

app/views/assignments/_assignment.html.slim
app/views/group_offers/show.html.slim

BugFix: remove not authorized links from volunteer ui

---

app/views/group_assignments/_volunteer_group_assignments.html.slim
test/system/department_manager_test.rb

BugFix: department-manager-can-show-volunteer

---

app/controllers/assignments_controller.rb
app/controllers/clients_controller.rb
app/controllers/group_offers_controller.rb
app/controllers/volunteers_controller.rb
app/models/assignment.rb
app/models/client.rb
app/models/concerns/group_assignment_and_assignment_scopes.rb
app/models/group_assignment.rb
app/models/group_offer.rb
app/models/performance_report.rb
app/models/volunteer.rb
test/integration/archived_group_offers_export_test.rb
test/integration/group_offers_xlsx_export_test.rb
test/models/assignment_scopes_test.rb
test/models/group_assignment_scopes_test.rb
test/models/group_offer_scopes_test.rb
test/models/performance_report_test.rb
test/models/volunteer_scopes_test.rb
test/system/volunteers_test.rb

Performance reports for group offer

---

app/models/hour.rb

dependent: :destroy shoudnt have been there0

---

app/models/group_offer.rb

BugFix: Issue 290

---

app/views/assignments/_assignment.html.slim
test/system/department_manager_test.rb

BugFix: department manager has no feedback links

---

app/views/performance_reports/show.html.slim
config/locales/de.yml
config/locales/en.yml
test/models/performance_report_test.rb
test/performance_report_generator.rb
test/system/performance_reports_test.rb
test/system/volunteers_test.rb

fix performance report show, and add test for it

---

app/models/assignment.rb
app/models/group_offer.rb
app/views/assignments/show.html.slim
app/views/certificates/_form.html.slim
app/views/volunteers/show.html.slim
test/system/certificates_test.rb

BugFix: Missing translations

---

app/views/departments/show.html.slim
app/views/users/edit.html.slim

remove back buttons for dep manager and social worker

---

app/models/assignment.rb
app/models/group_offer.rb
app/views/assignments/show.html.slim
app/views/certificates/_form.html.slim
app/views/certificates/show.pdf.slim
app/views/departments/edit.html.slim
app/views/departments/show.html.slim
app/views/group_assignments/_volunteer_group_assignments.html.slim
app/views/group_offers/show.html.slim
app/views/users/edit.html.slim
app/views/volunteers/show.html.slim
test/system/billing_expenses_test.rb
test/system/certificates_test.rb
test/system/group_offers_test.rb

merging latest fixes to master

---

app/views/application/_navigation.html.slim

Changes: display role in navigation

---

app/views/application/_footer.html.slim

Changes: modify footer

---

app/controllers/group_offers_controller.rb
app/models/group_offer.rb
app/models/user.rb
app/policies/group_offer_policy.rb
app/views/group_offers/_form.html.slim
config/locales/de.yml
db/migrate/20171031133535_add_group_offer_creator_relation.rb
db/schema.rb
db/seeds.rb
test/controllers/departments_controller_test.rb
test/factories/group_offers.rb
test/factories/users.rb
test/models/group_offer_test.rb
test/models/user_test.rb
test/policies/assignment_policy_test.rb
test/policies/client_policy_test.rb
test/policies/department_policy_test.rb
test/policies/group_offers_policy_test.rb
test/policies/hour_policy_test.rb
test/policies/journal_policy_test.rb
test/policies/profile_policy_test.rb
test/policies/user_policy_test.rb
test/system/department_manager_test.rb
test/system/departments_test.rb
test/system/group_offers_test.rb

Department manager can see own Group offers AKA validations for departmentmanager -> GroupOffer

---

app/controllers/users_controller.rb
app/views/users/index.html.slim
test/system/users_test.rb

Changes: Filter role on users index

---

README.md
db/seeds.rb

BugFix: Seeds run

---

.github/PULL_REQUEST_TEMPLATE.md

* ~[ ] Tested manually on staging~

Changes: no requirement for translation in definition of done

---

app/views/group_offers/_form.html.slim
app/views/group_offers/_group_assignment_fields.html.slim
config/locales/de.yml
config/locales/en.yml
test/system/group_offers_test.rb

BugFix: Volunteer collection should be present on group offer creation

---

app/views/application/_footer.html.slim

Fixes: Footer

---

app/assets/stylesheets/layout/_content.scss
app/assets/stylesheets/layout/_forms.scss
app/controllers/clients_controller.rb
app/models/client.rb
app/models/language_skill.rb
app/policies/client_policy.rb
app/views/clients/_client.html.slim
app/views/clients/_form.html.slim
app/views/clients/edit.html.slim
app/views/clients/new.html.slim
app/views/clients/show.html.slim
app/views/contacts/_fields.slim
app/views/relatives/_form.html.slim
config/locales/de.yml
config/locales/en.yml
test/system/clients_test.rb
test/test_helper.rb

Language Skills special for Client

---

app/views/application/_navigation.html.slim
app/views/assignments/index.html.slim
app/views/clients/index.html.slim
app/views/departments/show.html.slim
app/views/performance_reports/index.html.slim
app/views/users/index.html.slim
app/views/volunteers/index.html.slim
app/views/volunteers/index.xlsx.axlsx
app/views/volunteers/show.html.slim
config/locales/de.yml
config/locales/en.yml
test/system/department_manager_test.rb
test/system/departments_test.rb
test/system/feedbacks_test.rb
test/system/group_offers_test.rb
test/system/hours_test.rb
test/system/profiles_test.rb
test/system/sessions_test.rb
test/system/socialworker_test.rb

Changes: Removal of translations pt1 (navigation)

---

app/controllers/journals_controller.rb

Changes: Journal Create/Update redirects to Journal Index (Client)

---

db/migrate/20171109154536_add_index_to_contacts_tables_full_name_field.rb
db/schema.rb

add index to full_name field in order to gain better search performance

---

app/views/journals/_journal_block.html.slim
app/views/journals/index.html.slim

fix word_wrap using split on nil if journal.body is nil

---

app/controllers/users_controller.rb
app/controllers/volunteers_controller.rb
app/helpers/filter_dropdown_helper.rb
app/models/user.rb
app/models/volunteer.rb
app/views/users/index.html.slim
app/views/users/index.xlsx.axlsx
app/views/volunteers/index.html.slim
config/locales/de.yml
test/factories/volunteers.rb
test/integration/archived_group_offers_export_test.rb
test/integration/assignments_xlsx_export_test.rb
test/integration/clients_xlsx_export_test.rb
test/integration/group_offers_xlsx_export_test.rb
test/integration/users_xlsx_export_test.rb
test/integration/volunteers_xlsx_export_test.rb
test/models/volunteer_scopes_test.rb
test/test_helper.rb

> Except this one in question: "FW-Verantwortliche sollen nur ihre eigenen FW anschreiben können"

Generate Excel list for local MS-Office Mass Mailings

---

config/locales/de.yml

Fixes: missing german tranlation

---

app/controllers/assignments_controller.rb
app/controllers/group_assignments_controller.rb
app/policies/assignment_policy.rb
app/policies/group_assignment_policy.rb
app/views/application/_last_submitted_hours_and_feedbacks.html.slim
config/routes.rb
test/policies/assignment_policy_test.rb
test/policies/group_assignments_policy_test.rb
test/system/volunteer_submits_after_remind.rb

Fixes: Remove use of referer (replace update assignment/group assignment redirect only)

---

app/controllers/clients_controller.rb
test/system/client_notifications_test.rb

Fixes bugfix: If no active notification text (social worker creates client)

---

app/assets/stylesheets/layout/_navbar.scss
app/models/user.rb
app/views/application/_navigation.html.slim
test/system/feedbacks_test.rb
test/system/hours_test.rb
test/system/profiles_test.rb
test/system/sessions_test.rb
test/system/trial_feedbacks_test.rb

Changes: Navigation

---

app/models/user.rb
app/views/application/_navigation.html.slim
test/system/feedbacks_test.rb
test/system/hours_test.rb
test/system/profiles_test.rb
test/system/sessions_test.rb
test/system/trial_feedbacks_test.rb

Changes: Navigation changes (drop navigation name)

---

app/controllers/assignments_controller.rb
app/views/assignments/_assignment.html.slim
app/views/assignments/_assignments_block.html.slim
app/views/assignments/_assignments_table.xlsx.axlsx
app/views/assignments/_volunteer_index.html.slim
app/views/assignments/show.html.slim
app/views/clients/show.html.slim
app/views/volunteers/_columns.html.slim
config/locales/de.yml
config/locales/en.yml
test/integration/assignments_xlsx_export_test.rb
test/system/assignments_test.rb

Changes: Assignments

---

app/helpers/application_helper.rb
app/models/user.rb
app/views/departments/show.html.slim
app/views/users/_user.html.slim
test/system/departments_test.rb
test/system/users_test.rb

Fixes: fix link-name for users without account

---

app/views/assignments/_assignments_table.xlsx.axlsx
app/views/group_offers/show.html.slim
test/integration/assignments_xlsx_export_test.rb

Features/E-Mail Listen Exportieren für Begleitungen und Gruppenangebote

---

app/views/list_responses/feedbacks.html.slim
app/views/list_responses/trial_feedbacks.html.slim
test/system/list_response_feedbacks_test.rb
test/system/list_response_trial_feedbacks_test.rb

link for reviewed case was wrong

---

app/controllers/certificates_controller.rb
app/models/certificate.rb
app/models/group_assignment.rb
app/models/group_assignment_log.rb
app/models/group_offer_category.rb
app/models/volunteer.rb
app/views/certificates/_form.html.slim
app/views/certificates/show.html.slim
app/views/certificates/show.pdf.slim
test/integration/users_xlsx_export_test.rb
test/system/certificates_test.rb

Beim Dossier Freiwillig engagiert nur die effektiven Einsatzkategorien des Freiwilligen anzeigen

---

app/assets/stylesheets/layout/_content.scss
app/helpers/application_helper.rb
app/helpers/filter_dropdown_helper.rb
app/models/volunteer.rb
app/views/volunteers/_form.html.slim
app/views/volunteers/_volunteer.html.slim
app/views/volunteers/index.html.slim
config/locales/de.yml
config/locales/en.yml
db/migrate/20171220152759_add_invited_at_volunteer.rb
db/schema.rb
db/seeds.rb
test/system/volunteers_filter_dropdowns_test.rb
test/system/volunteers_test.rb

Changes: Volunteer state

---

app/views/application/_navigation.html.slim

Fixes: Add missing space on navigation

---

app/assets/stylesheets/layout/_content.scss
app/policies/volunteer_policy.rb
app/views/journals/_journal_block.html.slim
app/views/volunteers/_columns.html.slim
app/views/volunteers/_volunteer.html.slim
app/views/volunteers/index.html.slim
app/views/volunteers/show.html.slim
test/system/volunteers_test.rb

Changes: Affirmation changes volunteer

---

app/assets/stylesheets/layout/_content.scss
app/controllers/assignments_controller.rb
app/controllers/clients_controller.rb
app/controllers/volunteers_controller.rb
app/models/assignment.rb
app/models/client.rb
app/policies/client_policy.rb
app/views/clients/_client.html.slim
app/views/clients/_client_table.xlsx.axlsx
app/views/clients/_form.html.slim
app/views/clients/_listing_menu.html.slim
app/views/clients/_show_navigation.html.slim
app/views/clients/index.html.slim
app/views/clients/show.html.slim
config/locales/de.yml
config/locales/en.yml
db/migrate/20171221153738_change_client_state_to_acceptance.rb
db/schema.rb
db/seeds.rb
lib/access_import/transformers/client_transform.rb
test/integration/client_activeness_filter_test.rb
test/integration/client_activity_filter_test.rb
test/integration/clients_xlsx_export_test.rb
test/integration/volunteer_activity_filter_test.rb
test/models/assignment_scopes_test.rb
test/models/client_test.rb
test/models/department_test.rb
test/models/volunteer_test.rb
test/system/clients_filter_dropdowns_test.rb
test/system/clients_test.rb

Changes: Client Status

---

app/views/clients/show.html.slim

fixes/no unit-cost chosen view fix

---

app/policies/volunteer_policy.rb
test/policies/volunteer_policy_test.rb
test/system/volunteers_test.rb

Exclude social_worker from seeking_clients action

---

app/controllers/assignments_controller.rb
app/models/assignment.rb
app/models/client.rb
app/models/concerns/group_assignment_and_assignment_common.rb
app/models/concerns/volunteers_group_and_tandem_state_update.rb
app/models/group_assignment.rb
app/models/volunteer.rb
app/views/assignments/_assignment.html.slim
app/views/assignments/_assignments_block.html.slim
app/views/assignments/_assignments_table.xlsx.axlsx
app/views/assignments/_client_volunteer_index.html.slim
app/views/assignments/_form.html.slim
app/views/assignments/_listing_menu.html.slim
app/views/assignments/edit.html.slim
app/views/assignments/new.html.slim
config/locales/de.yml
config/locales/en.yml
db/migrate/20180104165600_remove_assignment_state.rb
db/schema.rb
lib/access_import/transformers/assignment_transform.rb
test/integration/assignments_xlsx_export_test.rb
test/models/assignment_scopes_test.rb
test/system/assignment_filters_test.rb
test/system/assignments_test.rb

changes/assignment active/inactive should be computed automatically

---

app/views/assignments/_listing_menu.html.slim
app/views/group_offers/index.html.slim

add placeholders to assignment search
