panter/aoz-003

app/views/application/_navigation.html.slim
test/system/profiles_test.rb

fix show profile link to lead to new_profile_path in case user has none

---

app/views/departments/show.html.slim

It was a quite mean bug because it doesn't bang in most cases.
Why:
Profile and User are almost always saved together. So on a fresh DB they will also almost always turn out to have the same `id`. Almost... ;)
And that's wat was not the case on the staging server, so linking like that didn't work there, but on our dev machines, it did.

fixing wrong path for user profile in departments

---

app/models/concerns/full_name.rb
app/models/relative.rb
app/models/volunteer.rb

This concern was actually only working in the Relatives model as is:
```ruby
def full_name
"#{first_name} #{last_name}"
end
```
In User and Volunteer, it could only crash the app, because:
```ruby
@user.profile.contact.first_name
@volunteer.contact.first_name
@relative.first_name
```
And, it was included into Volunteer as this, and it only didn't crash everything, because it was never used inside the Volunteer model. So remove it from Volunteer and put the working method to User and Relative.
Or in other words: **it was rather a bug, then a concern** ;)

fix the not working and obsolete full_name concern

---

app/models/client.rb
app/models/concerns/associate_relatives.rb
app/models/concerns/language_and_schedule_references.rb
app/models/volunteer.rb

removing concern used only in client and rename the other …
- associate relatives concern was only used in Client, so it
should be dropped and put into the client itself
- renaming the associatable_fields concern to a name that says
what the thing actually does

removing concern used only in client and rename the other

---

app/controllers/volunteers_controller.rb
test/system/volunteers_test.rb

add rejection fields to the params and show

---

app/models/language_skill.rb
app/views/language_skills/_show.html.slim
test/system/clients_test.rb

language level view on client/volunteer show and index

---

app/models/concerns/language_and_schedule_references.rb
app/models/language_skill.rb
app/views/volunteers/_volunteer.html.slim
db/migrate/20170807101812_add_originating_entity_to_imports.rb
db/schema.rb
lib/access_import/acc_utils.rb
lib/access_import/access_import.rb
lib/access_import/accessors/accessor.rb
lib/access_import/accessors/ausbildungen.rb
lib/access_import/accessors/begleitete.rb
lib/access_import/accessors/einsatz_orte.rb
lib/access_import/accessors/fallstellen.rb
lib/access_import/accessors/freiwilligen_einsaetze.rb
lib/access_import/accessors/freiwilligen_entschaedigung.rb
lib/access_import/accessors/journale.rb
lib/access_import/accessors/kontoangaben.rb
lib/access_import/accessors/laender.rb
lib/access_import/accessors/personen_rolle.rb
lib/access_import/accessors/sprache_pro_hauptperson.rb
lib/access_import/accessors/sprachen.rb
lib/access_import/accessors/stundenerfassung.rb
lib/access_import/client_transform.rb
lib/access_import/volunteer_transform.rb

* Languages where not imported correct
* foreign key mixup caused wrong language to be joined
* levels where mapped wrong
* creation time and update time are taken from the access db and used on the imported client and volunteer records.
* this allows to have usable sorting and more. I recon it would simply be terrible without
* Records that have a RollenEnde date present get RESIGNED (Volunteer) or FINISHED (Client) state
* Volunteers have a first_language collumn, that just displayed the first language in the list so far. That cannot be the propper implementation, because if there is multiple language_skills for a record, the chances are 50/50 at best, that this really is the natively spoken first language 😉

Fix to imports: Volunteers and Clients get status from t_RollenEnde plus bugfix with language_skills

---

app/views/volunteers/_volunteer.html.slim
lib/access_import/access_import.rb

- The flaw with User.first was, that I couldn't be sure that its a superadmin
- The User MUST have existed when the import ran.... but now it doesn't ???!
- But User.where(role: 'superadmin').first is the solution that should have
been there anyway
- It was there once, but it may have gone lost in rebaseing or other back and
forth while fullfilling review requirements

strange error with missing user id 1 on stageing

---

app/views/volunteers/show.html.slim

fix: Remove back button if volunteer is logged in

---

app/views/group_assignments/_volunteer_group_assignments.html.slim
config/locales/de.yml
config/locales/en.yml
test/system/group_offers_test.rb

BugFix: Group assignment agreement crashes when group assignment gets destroyed

---

app/views/reminders/index.html.slim

fix link to reminder.assignment.feedback link wrong

---

app/views/volunteers/show.html.slim
test/system/billing_expenses_test.rb
test/system/certificates_test.rb

BugFix: Billing Expenses & Certificate create depends also on Group Assignments

---

app/views/departments/edit.html.slim

Fixes: restrict back button department edit

---

app/views/group_assignments/_volunteer_group_assignments.html.slim

Fix: restrict edit group offer link on volunteer show

---

app/views/group_offers/show.html.slim
test/system/group_offers_test.rb

Fix: volunteer destroy doesnt destroy group offer show

---

app/controllers/volunteers_controller.rb
config/locales/de.yml
config/locales/en.yml
test/system/volunteers_test.rb

BugFix: Accepted on creation volunteers get invited

---

app/views/users/_form.html.slim
test/system/users_test.rb

Changes: superadmin can edit only their password

---

app/views/group_assignments/_volunteer_group_assignments.html.slim
test/system/volunteers_test.rb

BugFix: department manager links to group offers on volunteer show

---

.travis.yml
test/system/journals_test.rb

The test in `journals_test.rb`:
```ruby
test 'can_delete_a_journal_through_edit' do
Journal.with_deleted.map(&:really_destroy!)
create :journal, journalable: @volunteer
visit volunteer_path(@volunteer)
click_button 'Journal'
within '#journalBlock' do
click_link 'Edit'
end
page.find('a', text: 'Delete').click
assert page.has_text? 'Journal was successfully deleted.'
click_button 'Journal'
refute page.has_link? @journal_volunteer.user.full_name
refute page.has_text? @journal_volunteer.body
end
```
Test result locally:
```bash
$ rt -v -n '/can_delete_a_journal_through_edit/' test/system/journals_test.rb
Run options: -v -n /can_delete_a_journal_through_edit/ --seed 12702
...
JournalsTest#test_can_delete_a_journal_through_edit = 8.10 s = .
...
Finished in 8.101300s, 0.1234 runs/s, 0.3703 …
```

WIP: Find why travis fails on delete journal through edit & restore the test

---

app/views/volunteers/show.html.slim

After the last merge, the group offer category "Kurzbegleitungen bei wohnungsbezug in zürich-stadt" was shown as true on every volunteer. with the new changes, it should be fixed now.

fix group offer category volunteer show with zurich

---

app/views/application/_last_submitted_hours_and_feedbacks.html.slim
test/system/volunteer_submits_after_remind.rb

BugFix: Introduce time diff between created at and submitted at

---

test/factories/assignments.rb
test/factories/clients.rb
test/factories/feedbacks.rb
test/factories/group_assignment.rb
test/factories/group_offers.rb
test/factories/hours.rb
test/factories/trial_feedbacks.rb
test/factories/users.rb
test/policies/feedback_policy_test.rb
test/system/assignments_test.rb
test/system/billing_expenses_test.rb
test/system/feedbacks_test.rb
test/system/hours_test.rb

Sometimes running:
```ruby
FactoryBot.create(:feedback, author: @volunteer.user)
```
created a feedback with
```ruby
feedback.volunteer.user == feedback.author.volunteer.user # => false
```
and other impossible combinations.
FactoryBot `after(:build)` handlers over several factories take care of such trouble now.

Fix factories creating impossible volunteer relations

---

Gemfile
Gemfile.lock
app/helpers/application_helper.rb

.... or at least better maintained than the other one. Last update 2014 VS May 2017 ....

Will paginate bootstrap gem is not maintained anymore -> replace with similar that is maintained

---

app/helpers/application_helper.rb

Sory about the mess.  But now it really works.

BugFix: The new will_paginate renderer wasn't initialized right to make bootstrap pagination

---

app/assets/javascripts/volunteer_form.es6
test/system/volunteers_test.rb

Fixes: volunteer_experience_description_field_is_conditional

---

app/controllers/clients_controller.rb
test/system/client_notifications_test.rb

Fixes: Social worker always sees client notification text

---

app/controllers/feedbacks_controller.rb
app/controllers/hours_controller.rb
app/models/assignment.rb
app/models/group_assignment.rb
app/views/application/_last_submitted_hours_and_feedbacks.html.slim
app/views/feedbacks/_form.html.slim
app/views/hours/_form.html.slim
config/routes.rb

selected, no dropdown, so user can't accidently give feedback for wrong Einsatz
with something that makes use of get parameter

BugFix: Last submitted hours and feedbacks buggy new hour form and use of referer as redirect

---

app/assets/javascripts/all_turbolinks_on_load.es6
app/assets/javascripts/group_offer_form.es6
app/controllers/group_offers_controller.rb
app/views/group_offers/_form.html.slim
app/views/group_offers/_group_assignment_fields.html.slim
test/system/group_offers_test.rb

Fixes: Volunteer selection on group offer

---

app/views/volunteers/_volunteer.html.slim
config/locales/de.yml
config/locales/en.yml

Fixes: Find client button should appear once
